defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: feed-reader_development

test:
  <<: *defaults
  database: feed_reader_test

# set these environment variables on your prod server
production:
  host: 
  port:
  username: 
  password:
  database:
